export const BANGLADESH_DISTRICTS = [
  { name: "Bagerhat", division: "Khulna" },
  { name: "Bandarban", division: "Chattogram" },
  { name: "Barguna", division: "Barishal" },
  { name: "Barishal", division: "Barishal" },
  { name: "Bhola", division: "Barishal" },
  { name: "Bogura", division: "Rajshahi" },
  { name: "Brahmanbaria", division: "Chattogram" },
  { name: "Chandpur", division: "Chattogram" },
  { name: "Chapai Nawabganj", division: "Rajshahi" },
  { name: "Chattogram", division: "Chattogram" },
  { name: "Chuadanga", division: "Khulna" },
  { name: "Cox's Bazar", division: "Chattogram" },
  { name: "Cumilla", division: "Chattogram" },
  { name: "Dhaka", division: "Dhaka" },
  { name: "Dinajpur", division: "Rangpur" },
  { name: "Faridpur", division: "Dhaka" },
  { name: "Feni", division: "Chattogram" },
  { name: "Gaibandha", division: "Rangpur" },
  { name: "Gazipur", division: "Dhaka" },
  { name: "Gopalganj", division: "Dhaka" },
  { name: "Habiganj", division: "Sylhet" },
  { name: "Jamalpur", division: "Mymensingh" },
  { name: "Jashore", division: "Khulna" },
  { name: "Jhalokathi", division: "Barishal" },
  { name: "Jhenaidah", division: "Khulna" },
  { name: "Joypurhat", division: "Rajshahi" },
  { name: "Khagrachhari", division: "Chattogram" },
  { name: "Khulna", division: "Khulna" },
  { name: "Kishoreganj", division: "Dhaka" },
  { name: "Kurigram", division: "Rangpur" },
  { name: "Kushtia", division: "Khulna" },
  { name: "Lakshmipur", division: "Chattogram" },
  { name: "Lalmonirhat", division: "Rangpur" },
  { name: "Madaripur", division: "Dhaka" },
  { name: "Magura", division: "Khulna" },
  { name: "Manikganj", division: "Dhaka" },
  { name: "Meherpur", division: "Khulna" },
  { name: "Moulvibazar", division: "Sylhet" },
  { name: "Munshiganj", division: "Dhaka" },
  { name: "Mymensingh", division: "Mymensingh" },
  { name: "Naogaon", division: "Rajshahi" },
  { name: "Narail", division: "Khulna" },
  { name: "Narayanganj", division: "Dhaka" },
  { name: "Narsingdi", division: "Dhaka" },
  { name: "Natore", division: "Rajshahi" },
  { name: "Netrokona", division: "Mymensingh" },
  { name: "Nilphamari", division: "Rangpur" },
  { name: "Noakhali", division: "Chattogram" },
  { name: "Pabna", division: "Rajshahi" },
  { name: "Panchagarh", division: "Rangpur" },
  { name: "Patuakhali", division: "Barishal" },
  { name: "Pirojpur", division: "Barishal" },
  { name: "Rajbari", division: "Dhaka" },
  { name: "Rajshahi", division: "Rajshahi" },
  { name: "Rangamati", division: "Chattogram" },
  { name: "Rangpur", division: "Rangpur" },
  { name: "Satkhira", division: "Khulna" },
  { name: "Shariatpur", division: "Dhaka" },
  { name: "Sherpur", division: "Mymensingh" },
  { name: "Sirajganj", division: "Rajshahi" },
  { name: "Sunamganj", division: "Sylhet" },
  { name: "Sylhet", division: "Sylhet" },
  { name: "Tangail", division: "Dhaka" },
  { name: "Thakurgaon", division: "Rangpur" },
] as const;

export function slugifyCity(name: string) {
  return name
    .trim()
    .toLowerCase()
    .replace(/['.]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}
